FROM ubuntu:24.04 AS prep

RUN apt-get update && \
  apt-get install --no-install-recommends -y \
    chktex ghostscript lacheck latexmk latex-make latex-mk texlive \
    texlive-lang-german texlive-lang-english texlive-latex-extra \
    texlive-science texlive-font-utils && \
  apt-get clean -y

FROM prep AS tex

WORKDIR /tex
COPY .. /tex
RUN mkdir /out

RUN cd /tex

RUN latexmk -pdf Bachelorarbeit.tex

FROM scratch AS pdf

COPY --from=tex /tex/Bachelorarbeit.pdf /Bachelorarbeit.pdf
